server:
  port: 8065

spring:
  application:
    name: sc-lcn-demo-order-ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.10.237:3306/tcc_order?useUnicode=true&amp;characterEncoding=utf8
    username : root
    password : ckj3306!@#!
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:tcc_order;MODE=MYSQL;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis-plus:
  type-aliases-package: cn.jaychang.scstudy.order.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

hmily:
  tcc :
    serializer : kryo
    recoverDelayTime : 128
    retryMax : 30
    scheduledDelay : 128
    scheduledThreadMax :  10
    repositorySupport : db
    tccDbConfig :
       driverClassName  : com.mysql.jdbc.Driver
       url :  jdbc:mysql://10.1.10.237:3306/tcc?useUnicode=true&amp;characterEncoding=utf8
       username : root
       password : ckj3306!@#!
   # repositorySupport : redis
   #         hostName  : 192.168.1.68
   #         port      :  6379
   #         password  :


   # repositorySupport : zookeeper
   #         host      : 92.168.1.73:2181
   #         sessionTimeOut      :  100000
   #         rootPath  : /tcc

   # repositorySupport : mongodb
   #       mongoDbUrl  : 192.168.1.68:27017
   #       mongoDbName  :  happylife
   #       mongoUserName  : xiaoyu
   #       mongoUserPwd   : 123456

   # repositorySupport : file
   #         path      : /order
   #         prefix    :  order


logging:
  level:
    root: error
    org.springframework.web: info
    org.apache.ibatis: info
    com.baomidou.mybatisplus: info
    com.hmily.tcc.bonuspoint: debug
    com.hmily.tcc.lottery: debug
    com.hmily.tcc: debug
    io.netty: info
    cn.jaychang.scstudy.order: debug
  path: "./logs"
  file: ${spring.application.name}.log