server:
  port: 8061

spring:
  application:
    name: sc-myth-demo-account-ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.10.237:3306/tcc_account?useUnicode=true&amp;characterEncoding=utf8
    username : root
    password : ckj3306!@#!
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:tcc_account;MODE=MYSQL;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true

#  activemq:
#     broker-url: tcp://120.76.52.162:61616
#     user: happylife
#     password: happylifeplat01
#     trust-all: true
  rabbitmq:
      host: 171.188.0.165
      port: 5672
      username: guest
      password: guest
      addresses:
#  rocketmq:
#      namesrvAddr: 192.168.1.148:9876
#      consumerGroupName: account
#      instanceName: account
#  kafka:
#      consumer:
#         bootstrap-servers: localhost:9092
#         group-id: test
#         auto-offset-reset: earliest
#         enable-auto-commit: true
#         auto-commit-interval: 100
#        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#         value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis-plus:
  type-aliases-package: cn.jaychang.scstudy.account.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

com:
  github:
    myth:
      serializer: kryo
      repositorySupport: db
      mythDbConfig:
               driverClassName: com.mysql.jdbc.Driver
               url: jdbc:mysql://10.1.10.237:3306/myth?useUnicode=true&amp;characterEncoding=utf8
               username: root
               password: ckj3306!@#!

     # repositorySupport : redis
     #         hostName  : 192.168.1.68
     #         port      :  6379
     #         password  :


     # repositorySupport : zookeeper
     #         host      : 192.168.1.73:2181
     #         sessionTimeOut      :  100000
     #         rootPath  : /myth

     # repositorySupport : mongodb
     #       mongoDbUrl  : 192.168.1.68:27017
     #       mongoDbName  :  youname
     #       mongoUserName  : xiaoyu
     #       mongoUserPwd   : 123456

     # repositorySupport : file
     #         path      : /youpath
     #         prefix    :  youpath

logging:
  level:
    root: error
    org.springframework.web: info
    org.apache.ibatis: info
    com.baomidou.mybatisplus: info
    io.netty: info
    cn.jaychang.scstudy.account: debug
  path: "./logs"
  file: ${spring.application.name}.log