server:
  port: 8902
spring:
  cloud:
    stream:
      bindings:
        input:  # 普通的input，由spring cloud stream预先定义的，见@Sink
          destination: mqTestDefault
          group: demoConsumers
          binder: defaultRabbit
        inputOrder: # 自定义的
          destination: mqTestDefault # 就是rabbitmq的交换机
          group: inputOrderConsumers # 就是rabbitmq的队列名
          binder: defaultRabbit
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 171.188.0.165
                port: 5672
                username: guest
                password: guest
                virtual-host: dev
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: test.*
          inputOrder:
            consumer:
              bindingRoutingKey: orderAdd # 建议还是用这种好了
#  rabbitmq:
#    host: 171.188.0.165
#    port: 5672
#    username: guest
#    password: guest

logging:
  level:
    root: info
    cn.jaychang.scstudy: debug




