server:
  port: 8883
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
  instance:
    prefer-ip-address: true
spring:
  application:
    name: sc-config-server-v3
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jaychang/springcloud-tutorial.git
          username:
          password:
          search-paths: repo



