server:
  port: 8901
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: mqTestDefault
          contentType: text/plain
          binder: defaultRabbit
        outputOrder:
          destination: mqTestDefault
          contentType: application/json
          binder: defaultRabbit
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 171.188.0.165
                port: 5672
                username: guest
                password: guest
                virtual-host: dev
      rabbit:
        bindings:
          output:
            producer:
              routing-key-expression: '''test.*'''
          outputOrder:
            producer:
              routing-key-expression: '''order.add'''
logging:
  level:
    root: info
    org.springframework.cloud.stream: debug
    cn.jaychang.scstudy: debug